name: 10.Env.Demo

on: workflow_dispatch
env: 
    APP_ENV: "DEV"
jobs:
    env_demo:
        env:
            APP_ENV: "QA"
        runs-on: ubuntu-latest
        steps:
            - name: Connecting to ENV
              env: 
                APP_ENV: "PROD"
              run: echo "App is connecting to $APP_ENV"