name: 11.Inputs Demo
on: 
    workflow_dispatch:
        inputs:
            environment:
                description: choose the env to deploy
                required: true
                default: dev
                type: choice
                options:
                    - DEV
                    - QA
                    - STG
                    - PROD
            artifact_tag:
                description: Choose the right Tag to Deploy
                required: true 
jobs:
    inputs-demo:
        runs-on: ubuntu-latest
        steps:
        - name: Deploy the App
          run: echo "Deploying the ${{inputs.artifact_tag}} Application to ${{inputs.environment}}"




