name: 14.if-Demo
on:
    push:
        branches:
            - main
            - develop
jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
          - name: Run if Branch is Main 
            #if: github.ref == 'refs/heads/main'
            if: github.ref_name == 'main'
            run: echo "Running this Step"
          - name: Run this Step
            run: echo "Running this Step"